283c: The Science of Insecurity
hellerve/programming-talks pull request #110
Opened 2022-07-11 15:14 UTC by AmosAidoo

2022-07-13 21:09 UTC, hellerve commented
Thanks for your contribution!

Just a heads-up: I’m currently on vacation, travelling around, and will probably not be able to watch the talk/review the PR until early next week.

2022-07-13 23:20 UTC, AmosAidoo commented
> Thanks for your contribution!
> 
> Just a heads-up: I’m currently on vacation, travelling around, and will probably not be able to watch the talk/review the PR until early next week.

Sure no problem🙂. You are definitely going to enjoy the talk

2022-07-18 16:55 UTC, hellerve requested changes
Well that was fun!

Just one minor thing, then we’re good to go!

2022-07-18 16:55 UTC, hellerve commented on README.md
> +* [283c: The Science of Insecurity](https://www.youtube.com/watch?v=3kEfedtQVOY) [00:59:22] by **Meredith L. Patterson, Sergey** (2011)
Looks like there is a typo here:
```suggestion
* [28c3: The Science of Insecurity](https://www.youtube.com/watch?v=3kEfedtQVOY) [00:59:22] by **Meredith L. Patterson, Sergey** (2011)
```

2022-07-18 17:58 UTC, AmosAidoo commented
I've made the change, thanks

2022-07-18 19:44 UTC, hellerve approved these changes
Thank you 😸

2022-07-18 19:44 UTC, merged